# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7aqn6njkGM25CTpOItV6DItdUVix0Da
"""

#Main Quiz

from quiz import get_questions, check_answer
from score import calculate_score, check_pass

def ask_questions():
    questions = get_questions()
    correct_count = 0

    for question, options in questions.items():
        print("\n" + question)
        for option in options:
            print(option)

        user_answer = input("Enter your answer (A/B/C/D): ")

        if check_answer(question, user_answer):
            print("Correct!")
            correct_count += 1
        else:
            print("Incorrect!")

    return correct_count, len(questions)

def display_results(score):
    if check_pass(score):
        print(f"\nCongratulations! You passed the quiz with a score of {score}.")
    else:
        print(f"\nSorry, You failed the quiz. Your score is {score}.")

def main():
  print ("Welcome to the Quiz Application!")
  correct_count, total_questions = ask_questions()
  score = calculate_score(correct_count, total_questions)
  display_results(score)

if __name__ == "__main__":
    main()