# -*- coding: utf-8 -*-
"""quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13l8ETRTYTj7Bp0COgX_dE1rsjH6qz9gA
"""

#Quiz Questions.

question = {
    "What is the capital of Nigeria?":["A. Lagos", "B. Abuja", "C. Delta", "D. Gombe"],
    "Who is the father of computer?":["A. Charles Babbage", "B. Charles Sawyer", "C. Charles Spurgeon", "D. Charles Graham"],
    "How many planets are in our solar system?":["A. 7", "B. 8", "C. 9", "D. 10"],
    "How many colors are in a rainbow?":["A. 7", "B. 8", "C. 9", "D. 10"],

}

#Quiz Answers.

answers = {
    "What is the capital of Nigeria?":"B",
    "Who is the father of computer?":"A",
    "How many planets are in our solar system?":"B",
    "How many colors are in a rainbow?":"A",
}

def get_questions():
  return question

def get_answers():
    return answers

def check_answer(question, user_answer):
  correct_answer = answers[question]
  return user_answer == correct_answer
