# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWylj0QzT2HVTZWK7qZB3lr1LBNuGuTt
"""

#Scores

Pass_Mark = 50

def calculate_score(correct_count, total_questions):
  return (correct_count / total_questions) * 100

def check_pass(score):
  if score >= Pass_Mark:
    return "Pass"
  else:
    return "Fail"